version: "3.8"
services:
  express_app:
    container_name: express_app
    build: ./Docker/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - express_redis

  express_redis:
    container_name: express_redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  express_nginx:
    container_name: express_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - express_app
    networks:
      - express_network

  # express_certbot:
  #   container_name: express_certbot
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - express_nginx
  #   entrypoint: >
  #     sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
  #     --email your-email@example.com --agree-tos --no-eff-email
  #     --staging -d yourdomain.com"

networks:
  express_network:
    driver: bridge
